export const INITIAL_SCHEMA = `
CREATE TABLE IF NOT EXISTS Books (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  filename TEXT NOT NULL,
  file_path TEXT NOT NULL,
  file_type TEXT NOT NULL,
  total_pages INTEGER DEFAULT 0,
  current_page INTEGER DEFAULT 1,
  added_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE Books ADD COLUMN is_pinned INTEGER DEFAULT 0;
ALTER TABLE Books ADD COLUMN author TEXT DEFAULT '';
ALTER TABLE Books ADD COLUMN genre TEXT DEFAULT '';
ALTER TABLE Books ADD COLUMN published_year TEXT DEFAULT '';
ALTER TABLE Books ADD COLUMN description TEXT DEFAULT '';
ALTER TABLE Books ADD COLUMN cover_image TEXT DEFAULT '';
ALTER TABLE Books ADD COLUMN sort_order INTEGER DEFAULT 0;

CREATE TABLE IF NOT EXISTS Annotations (
  id TEXT PRIMARY KEY,
  book_id TEXT NOT NULL,
  type TEXT NOT NULL,
  content TEXT,
  page INTEGER NOT NULL,
  position_data TEXT NOT NULL,
  color TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (book_id) REFERENCES Books(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Notes (
  id TEXT PRIMARY KEY,
  book_id TEXT NOT NULL,
  target_text TEXT,
  note_content TEXT NOT NULL,
  page INTEGER NOT NULL,
  position_data TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (book_id) REFERENCES Books(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ReadingHistory (
  id TEXT PRIMARY KEY,
  book_id TEXT NOT NULL,
  read_date DATE NOT NULL,
  duration_seconds INTEGER DEFAULT 0,
  pages_read INTEGER DEFAULT 0,
  UNIQUE(book_id, read_date),
  FOREIGN KEY (book_id) REFERENCES Books(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Bookmarks (
  id TEXT PRIMARY KEY,
  book_id TEXT NOT NULL,
  page INTEGER NOT NULL,
  title TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (book_id) REFERENCES Books(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TableOfContents (
  id TEXT PRIMARY KEY,
  book_id TEXT NOT NULL,
  title TEXT NOT NULL,
  page INTEGER NOT NULL,
  parent_id TEXT,
  order_index INTEGER DEFAULT 0,
  FOREIGN KEY (book_id) REFERENCES Books(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);
`;
